### ISSUE TITLE
How to classify and deal with multiple configurations

### ISSUE THREAD

**Issue by GregAC** [lowRISC/ibex#857]
The current multi-config setup for Ibex is simple. We have a number of named configs and they all supply settings for the same parameters, this is one example:

https://github.com/lowRISC/ibex/blob/863fb56eb166dc8d6e25f4e98b7319f0c7088564/ibex_configs.yaml#L10-L16

Are we happy with this setup or do want something more complex? In particular for PMP this isn't really something that pairs nicely with a 'high performance' config you could equally want it with the lower performance or higher performance config. We could define multiple configs one with -pmp one without to have every config (or some subset of them) with pmp on or off (so you'd have a `small-3cmult-pmp-off` and a `small-3cmult-pmp-on`. Alternatively we could introduce config 'add-ons'. Extra bits in the YAML file that could be paired with any config:

```yaml
pmp16-on:
  PMPRegions: 16
  PMPGranularity: 0
```

This would be given to `ibex_config.py` along with the main config name

```
./util/ibex_config.py experimental-maxperf-bm-1cmult pmp16-on fusesoc_opts
```

I was tending towards the config add-ons option, as doing multiple configs with names like '-pmp-on' doesn't scale very well.

(Lets try and divorce this from the what is a supported configuration discussion, my view is we can define supported configs in the documentation and flag them specifically in the `ibex_configs.yaml` but it can still give functionality/parameters for non-supported configs, we could even add a warning output from `ibex_config.py` if you use an unsupported config setup).

**Comment by rswarbrick** [comment]
I like the config add-ons approach. It would probably be good if we could also "name" some collections of add-ons, so there would be a "for-opentitan" config etc.

**Comment by GregAC** [comment]
Perhaps I should lean more heavily on the add-ons approach and everything becomes an 'add-on' then a 'config' becomes a collection of add-ons and individual parameter settings.

```yaml
high-perf:
  RV32E                    : 0
  RV32M                    : 1
  BranchTargetALU          : 1
  WritebackStage           : 1
  MultiplierImplementation : "single-cycle"

pmp16-on:
  PMPRegions: 16
  PMPGranularity: 0

...

opentitan:
  high-perf
  pmp16-on
  RV32B : 1
```

Or just drop the whole seperation between 'add-ons' and 'configs', everything is a config and configs can include other configs?
